"""ANTSState — LangGraph StateGraph definition for the ANTS workflow."""

from __future__ import annotations

from typing import Annotated, Literal, TypedDict

from langgraph.graph.message import add_messages


class TaskItem(TypedDict):
    id: str
    title: str
    description: str
    assigned_agent: str
    phase: int
    depends_on: list[str]
    status: Literal["pending", "in_progress", "completed", "needs_redo", "skipped"]
    output: dict | None


class AgentPlanItem(TypedDict):
    """Describes a single sub-agent that the Planner wants to create.

    The Supervisor Agent iterates over ``agent_plan`` items, instantiates
    a ``SubAgent`` loaded with the specified skills, and assigns it the
    listed tasks.
    """

    phase_name: str           # e.g. "requirements", "design", "development", "testing"
    agent_id: str             # unique id like "sub_coder_task_001"
    skill_names: list[str]    # skills to load (see SkillRegistry built-ins)
    task_ids: list[str]       # task IDs assigned to this sub-agent


class ANTSState(TypedDict):
    # ── Session core ────────────────────────────────────────────────
    session_id: str
    goal: str
    project_path: str
    current_phase: int          # 1=planning, 2=execution, 3=verification

    # ── Task management ─────────────────────────────────────────────
    tasks: list[TaskItem]       # Produced by Planner, updated by Orchestrator
    current_task_id: str | None

    # ── Agent plan (skill-based sub-agents) ─────────────────────────
    agent_plan: list[AgentPlanItem]   # Sub-agents with skills, generated by Planner
    loaded_skill_names: list[str]     # All skill names referenced in agent_plan

    # ── Messages / memory ───────────────────────────────────────────
    messages: Annotated[list, add_messages]  # Streaming-compatible message flow
    session_memory: str         # Accumulated step summary (each node appends)

    # ── Experience context (progressive disclosure state) ───────────
    experience_budget_used: int           # Tokens spent on experiences so far
    injected_experience_ids: list[str]    # IDs already injected (avoid dupes)

    # ── Human-in-the-loop ───────────────────────────────────────────
    human_decision: str | None   # "approve" | "redo" | "edit" | "abort"
    human_note: str | None

    # ── Flow control ────────────────────────────────────────────────
    phase_status: Literal["running", "waiting_human", "completed"]
    workflow_status: Literal["running", "paused", "completed", "aborted"]

